#!/bin/sh
#
# Copyright (C) 2011-2012 OpenWrt.org
#

[ -e /etc/config/ubootenv ] && exit 0

touch /etc/config/ubootenv

. /lib/uboot-envtools.sh
. /lib/functions.sh

kroks_setup_env() {
	local board="$1"

	case "$board" in
	ap205m1|\
	ap221|\
	ap221m3|\
	ap221m4|\
	ap222|\
	ap223|\
	ap223m1|\
	ap223m3|\
	kndrt22r*|\
	kndrt31r*)
		ubootenv_add_uci_config "/dev/mtd1" "0x0" "0x1000" "0x10000"
		;;
	esac
}

board=$(board_name)

case "$board" in
alfa-network,ac1200rm|\
alfa-network,awusfree1|\
alfa-network,quad-e4g|\
alfa-network,r36m-e4g|\
alfa-network,tube-e4g)
	ubootenv_add_uci_config "/dev/mtd1" "0x0" "0x1000" "0x1000"
	;;
all0256n-4M|\
all0256n-8M|\
all5002)
	ubootenv_add_uci_config "/dev/mtd1" "0x0" "0x10000" "0x10000"
	;;
linkits7688|\
miwifi-nano|\
sk-wb8|\
wsr-1166|\
wsr-600|\
zbt-wg2626)
	ubootenv_add_uci_config "/dev/mtd1" "0x0" "0x1000" "0x10000"
	;;
xiaomi,mir3p|\
xiaomi,mir3g)
	ubootenv_add_uci_config "/dev/mtd1" "0x0" "0x1000" "0x20000"
	;;
*)
	kroks_setup_env "$board"
	;;
esac

config_load ubootenv
config_foreach ubootenv_add_app_config ubootenv

exit 0
